<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MarkZither.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <AssemblyName>MarkZither.$(MSBuildProjectName)</AssemblyName>
    <UserSecretsId>7ed23aa8-26a4-4992-b8f9-9868e6052b39</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MarkZither.KimaiDotNet.ApiClient" Version="0.4.0-beta0001" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
    <PackageReference Include="Polly.Core" Version="8.4.2" />
    <PackageReference Include="Microsoft.OpenApi.OData" Version="3.2.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.5.4" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

</Project>
